server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
  redis:
    host: 192.168.2.2
    port: 6379
    database: 0
    password: ''
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 8     #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8       #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
        min-idle: 0       #最小等待连接中的数量,设 0 为没有限制
  kafka:
    producer:
      acks:
    consumer:
      auto-commit-interval:
    listener:
      ack-count: 
#mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

